version: '3.3'

services:
  mysql:
    container_name: kudl-db
    image: kudl1229/kudl-db:0.0.1
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=kudl
      - MYSQL_USER=kudl
      - MYSQL_PASSWORD=kudl
      - MYSQL_DATABASE=kudlwork
      - TZ=Asia/Seoul
